language: node_js
node_js:
- '0.12'
services:
- mongodb
deploy:
  app: icicle-kindling
  provider: heroku
  api_key:
    secure: p5z+lV3vOa7GAUj4a8j/GiWVy98aISHNnB15bQXlEqV2TTXwpi8AS3F/4lxIPSHzlIUBJzM5e0qhxhmhBtOu8o/wqZADd1X4MzkEKIP6Po3kk3qJ7CQkJlzH8dy6A9fAZrxFGPdXBwZi4mxAvnhYn/G5du6n5HoKdFFhF6DCkEulNxaNaUUCft77pVDJAxSME852OeJHg0DhxA53N/vc3mAKjcyqbdlFhQJl9d5PZ0eDPyt+usI5/5Pkq5Swu+I3qPVN9EUTE1CRepdVvGBGXA9L7JDeXt+tWUHVFvXAqB/Ckf7Q+YuqiPB+kLY9lgMzrqN850LzQ2DoA/qFHO7BU3zNqjv2KDgcgVo48bB9T2UTT8D1MCwtBhWdivjdXME9fUAfzszTZqE8VTxSWTFdY6zm6ey95JNuzwGwbEYC41fEqbaDwY7VarzWEGnbwyhrLmjpMbp0tQZxFi8SYhhVT8Ki5Wn8olN+rDSGdni6EK1bAppbVudJZRqPER0Q4kETzbG+tLt0y1ZHmdyPFH/vV2W31Y61hBLcTEFFYDRDKJxOSBqfbHVlcUMODP5Ey13mFKJoORX1kQu37D0gmxOaqqZZ4zgz2lREj81rwZibfhN3ROAUAu1z0Zw59RPI+fOQFmKofls2qPCj1Z7H5vYnfwzbdpGa8IhWahC/S7uWXrI=
